shutdown_costmaps: false

controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0

scillation_timeout: 10.0
oscillation_distance: 0.2


aggressive_reset1:
  reset_distance: 4
  layer_names: ["rs_st_obstacle_layer"]

